DROP TABLE IF EXISTS users
CASCADE;

DROP TABLE IF EXISTS properties
CASCADE;

CREATE TABLE users
(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL
);

